services:
    # Três serviços usando a mesma imagem do Dockerfile na raiz
    api1:
        build: .
        image: postcardd-server:latest
        env_file: .env
        restart: unless-stopped
    
    api2:
        image: postcardd-server:latest
        env_file: .env
        restart: unless-stopped
        depends_on:
            - api1
    
    api3:
        image: postcardd-server:latest
        env_file: .env
        restart: unless-stopped
        depends_on:
            - api1

    # Proxy reverso para os 3 serviços backend, distribuindo via round-robin por padrão
    nginx:
        image: nginx:alpine
        ports:
            - "8000:80" # Única porta exposta ao mundo nessa instância
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
        depends_on:
            - api1
            - api2
            - api3
        restart: unless-stopped